#!/bin/dash

if [ -d /etc/X11/xinit/xinitrc.d ]
then (
 for f in /etc/X11/xinit/xinitrc.d/?*.sh
  do [ -x "$f" ] && . "$f"
 done
) fi

# load resources
xrdb -DSOLARIZED_DARK -merge "$XDG_CONFIG_HOME"/xorg/db

# set root window's pointer cursor
xsetroot -cursor_name left_ptr
# keyboard rate
xset r rate 200 80

# 'night shift'
redshift &

# key bindings
xbindkeys -fg "$XDG_CONFIG_HOME"/xbindkeys/xbindkeys.scm

export XMONAD_CONFIG_DIR="$XDG_CONFIG_HOME"/xmonad
export XMONAD_CACHE_DIR="$XDG_RUNTIME_DIR"/xmonad
export XMONAD_DATA_DIR="$XDG_DATA_HOME"/xmonad

mkdir -p "$XMONAD_CACHE_DIR"
mkdir -p "$XMONAD_DATA_DIR"

# window manager
exec xmonad
