#!/bin/dash

if [ -d /etc/X11/xinit/xinitrc.d ]
then (
 for f in /etc/X11/xinit/xinitrc.d/?*.sh
  do [ -x "$f" ] && . "$f"
 done
) fi

# load resources
xrdb -DSOLARIZED_DARK -merge "$home"/.Xresources
# set background image
xsetbg -fullscreen -tile "$home"/.icons/wallpaper.png
# set root window's pointer cursor
xsetroot -cursor_name left_ptr

# keyboard rate
xset r rate 200 80
# 'night shift'
redshift &

xbindkeys -fg "$cfg"/xbindkeys/xbindkeys.scm

export XMONAD_CONFIG_DIR="$cfg"/xmonad
export XMONAD_CACHE_DIR="$run"/xmonad
export XMONAD_DATA_DIR="$dat"/xmonad

mkdir -p "$XMONAD_CACHE_DIR"
mkdir -p "$XMONAD_DATA_DIR"

# window manager
exec xmonad
